import { describe, expect, test } from "bun:test";
import {
  A2A_METHOD,
  AGENT_CARD_PATH,
  assertAllowlisted,
  decodeRequest,
  encodeError,
  encodeMessage,
  encodeResult,
  MESSAGE_FIELD_ALLOWLIST,
  PART_FIELD_ALLOWLIST,
  RPC_PATH,
  splitSystemUser,
  WireError,
} from "../src/a2a/wire.ts";

const golden = (name: string) =>
  Bun.file(new URL(`./fixtures/golden/${name}`, import.meta.url)).json();

describe("A2A wire constants match the pinned protocol crawl", () => {
  test("paths and method are the ones the evaluator uses", () => {
    // a2a-python/src/a2a/utils/constants.py (crawled 2026-08-24)
    expect(AGENT_CARD_PATH).toBe("/.well-known/agent-card.json");
    expect(RPC_PATH).toBe("/");
    // sync_client.py::build_send_message_jsonrpc_request
    expect(A2A_METHOD).toBe("SendMessage");
  });

  test("allowlists match a2a.proto exactly", () => {
    // specification/a2a.proto: message Message / message Part (crawled 2026-08-24)
    expect([...MESSAGE_FIELD_ALLOWLIST]).toEqual([
      "messageId",
      "contextId",
      "taskId",
      "role",
      "parts",
      "metadata",
      "extensions",
      "referenceTaskIds",
    ]);
    expect([...PART_FIELD_ALLOWLIST]).toEqual([
      "text",
      "raw",
      "url",
      "data",
      "metadata",
      "filename",
      "mediaType",
    ]);
  });
});

describe("decode — golden frames generated by the REAL python a2a-sdk serializer", () => {
  test("first turn: System/User text part + tools data part", async () => {
    const { turn } = decodeRequest(await golden("request-first.json"));

    expect(turn.kind).toBe("first");
    expect(turn.systemPrompt).toContain("In-Car Assistant agent policy");
    expect(turn.userText).toBe("Open the sunroof halfway.");
    expect(turn.tools?.length).toBe(2);
    expect(turn.source).toBe("user");
    // The evaluator sends no contextId on the first turn (G-H).
    expect(turn.contextId).toBeNull();
  });

  test("tool-results turn", async () => {
    const { turn } = decodeRequest(await golden("request-tool-results.json"));

    expect(turn.kind).toBe("tool-results");
    expect(turn.contextId).toBe("ctx-abc");
    expect(turn.source).toBe("environment");
    expect(turn.toolResults).toEqual([
      { toolName: "get_weather", toolCallId: "call_1", content: '{"condition":"sunny"}' },
    ]);
  });

  test("plain user follow-up turn", async () => {
    const { turn } = decodeRequest(await golden("request-user.json"));

    expect(turn.kind).toBe("user");
    expect(turn.userText).toBe("Yes, please.");
    expect(turn.contextId).toBe("ctx-abc");
  });

  test("the empty-message sentinel is handled", () => {
    const { turn } = decodeRequest({
      jsonrpc: "2.0",
      id: "1",
      method: "SendMessage",
      params: { message: { messageId: "m", role: "ROLE_USER", parts: [{ text: "   " }] } },
    });
    expect(turn.userText).toBe("none");
  });

  test("malformed frames raise a typed WireError instead of crashing", () => {
    expect(() => decodeRequest("nope")).toThrow(WireError);
    expect(() => decodeRequest({ method: "Other", params: {} })).toThrow(WireError);
    expect(() => decodeRequest({ method: "SendMessage" })).toThrow(WireError);
  });

  test("splitSystemUser is exact about the documented delimiter", () => {
    expect(splitSystemUser("System: P\n\nUser: U")).toEqual({ systemPrompt: "P", userText: "U" });
    expect(splitSystemUser("just a user message")).toEqual({
      systemPrompt: null,
      userText: "just a user message",
    });
  });
});

describe("encode — strict allowlist (architect RULING 1)", () => {
  test("text-only response", () => {
    const message = encodeMessage({ text: "Sunroof is open.", toolCalls: [] }, "ctx-1", "msg-1");
    expect(message).toEqual({
      messageId: "msg-1",
      contextId: "ctx-1",
      role: "ROLE_AGENT",
      parts: [{ text: "Sunroof is open." }],
    });
    expect(() => assertAllowlisted(message)).not.toThrow();
  });

  test("tool calls go in a data part as {tool_calls:[{tool_name, arguments}]}", () => {
    const message = encodeMessage(
      { toolCalls: [{ toolName: "get_weather", arguments: { location_or_poi_id: "loc_1" } }] },
      "ctx-1",
      "msg-2",
    );
    expect(message.parts).toEqual([
      {
        data: {
          tool_calls: [{ tool_name: "get_weather", arguments: { location_or_poi_id: "loc_1" } }],
        },
      },
    ]);
  });

  test("turn_metrics rides in metadata, never in a part", () => {
    const message = encodeMessage(
      { text: "done", toolCalls: [], turnMetrics: { prompt_tokens: 10, num_passes: 1 } },
      "ctx-1",
      "msg-3",
    );
    expect(message.metadata).toEqual({ turn_metrics: { prompt_tokens: 10, num_passes: 1 } });
    expect(JSON.stringify(message.parts)).not.toContain("turn_metrics");
  });

  test("an empty step still produces a valid parts array (parts is REQUIRED)", () => {
    const message = encodeMessage({ toolCalls: [] }, "ctx-1", "msg-4");
    expect(message.parts).toEqual([{ text: "" }]);
    expect(() => assertAllowlisted(message)).not.toThrow();
  });

  // ── MANDATORY NEGATIVE CONTRACT TEST (RULING 1) ─────────────────────────────────────────────
  test("NEGATIVE: a polluted message is REJECTED by the allowlist", () => {
    const polluted = {
      ...encodeMessage({ text: "hi", toolCalls: [] }, "ctx-1", "msg-5"),
      thinking: "leaked internal field",
    };
    expect(() => assertAllowlisted(polluted)).toThrow(/not in the a2a.v1.Message allowlist/);
  });

  test("NEGATIVE: a polluted PART is rejected", () => {
    const message = encodeMessage({ text: "hi", toolCalls: [] }, "ctx-1", "msg-6");
    const firstPart = (message.parts as Record<string, unknown>[])[0];
    if (firstPart) firstPart.kind = "text"; // v0.3 spelling, invalid in 1.0
    expect(() => assertAllowlisted(message)).toThrow(/not in the a2a.v1.Part allowlist/);
  });

  test("NEGATIVE: a wrong role is rejected", () => {
    const message = encodeMessage({ text: "hi", toolCalls: [] }, "ctx-1", "msg-7");
    message.role = "agent";
    expect(() => assertAllowlisted(message)).toThrow(/ROLE_AGENT/);
  });

  test("JSON-RPC envelopes echo the request id", () => {
    expect(encodeResult({ messageId: "m" }, "req-9")).toEqual({
      jsonrpc: "2.0",
      id: "req-9",
      result: { message: { messageId: "m" } },
    });
    const err = encodeError(new WireError("bad", -32601), "req-9") as Record<string, any>;
    expect(err.error.code).toBe(-32601);
  });
});
