"""Shared pytest fixtures. All geometry is GENERATED by build123d — nothing is downloaded."""

from __future__ import annotations

import sys
from pathlib import Path

import build123d as bd
import pytest

sys.path.insert(0, str(Path(__file__).parent))
# The DEV profile. `cadtools_devtools` is a separate distribution that an eval venv does not
# install (F-003); the test suite is the dev profile by definition, so it is put on the path
# here rather than requiring a second editable install to run the tests.
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "devtools"))

from fixtures import (  # noqa: E402
    make_box,
    make_ell_prism,
    make_ell_prism_padded_by_bbox,
    make_ell_prism_padded_by_profile,
    make_hollow_ball,
    make_open_shell,
    make_plate,
    make_plate_with_blind_pocket,
    make_plate_with_corner_hole,
    make_plate_with_through_hole,
    make_side_flat_dome,
    make_sliver_face_part,
    make_thicker_plate,
    make_two_disjoint_blocks,
    write_step,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = REPO_ROOT / ".mutagent" / "specs" / "cad-step-editor" / "agentspec.yaml"
AGENT_MD_PATH = REPO_ROOT / ".claude" / "agents" / "mutagent-brepsmith.md"


class NetworkAccessDenied(RuntimeError):
    """Raised when a test attempts to open a network connection."""


@pytest.fixture(autouse=True, scope="session")
def _block_network() -> object:
    """The BUILD suite is offline by construction (T16, Risk R6).

    Every fixture is GENERATED by build123d, never downloaded, so a test that reaches the
    network is a defect — either a hidden download or an accidentally-live dataset call.
    Rather than grepping test sources for suspicious tokens, the socket layer is closed for
    the whole session, which catches it however it is spelled.
    """
    import socket

    real_connect = socket.socket.connect
    real_create = socket.create_connection

    def deny(*args: object, **kwargs: object) -> None:
        raise NetworkAccessDenied(
            "the BUILD test suite is offline by construction; generate fixtures with "
            "build123d instead of downloading them"
        )

    socket.socket.connect = deny  # type: ignore[method-assign]
    socket.create_connection = deny  # type: ignore[assignment]
    try:
        yield None
    finally:
        socket.socket.connect = real_connect  # type: ignore[method-assign]
        socket.create_connection = real_create  # type: ignore[assignment]


@pytest.fixture(scope="session")
def repo_root() -> Path:
    return REPO_ROOT


@pytest.fixture(scope="session")
def spec_path() -> Path:
    return SPEC_PATH


@pytest.fixture(scope="session")
def agent_md_path() -> Path:
    return AGENT_MD_PATH


@pytest.fixture(scope="session")
def box() -> bd.Solid:
    return make_box()


@pytest.fixture(scope="session")
def plate() -> bd.Solid:
    return make_plate()


@pytest.fixture(scope="session")
def plate_with_through_hole() -> bd.Solid:
    return make_plate_with_through_hole()


@pytest.fixture(scope="session")
def plate_with_blind_pocket() -> bd.Solid:
    return make_plate_with_blind_pocket()


@pytest.fixture(scope="session")
def plate_with_corner_hole() -> bd.Solid:
    return make_plate_with_corner_hole()


@pytest.fixture(scope="session")
def thicker_plate() -> bd.Solid:
    return make_thicker_plate()


@pytest.fixture(scope="session")
def two_disjoint_blocks() -> bd.Compound:
    return make_two_disjoint_blocks()


# --- the abc_0352 class (run-003 F-005): same bbox, different cross-section ---------


@pytest.fixture(scope="session")
def ell_prism() -> bd.Solid:
    """The 'before' body: an L-section prism whose +X face is NOT its bounding rectangle."""
    return make_ell_prism()


@pytest.fixture(scope="session")
def ell_prism_padded_by_profile() -> bd.Solid:
    """The CORRECT +X pad — the face's own profile swept."""
    return make_ell_prism_padded_by_profile()


@pytest.fixture(scope="session")
def ell_prism_padded_by_bbox() -> bd.Solid:
    """The DEFECTIVE +X pad — the face's bounding RECTANGLE swept. Identical bbox."""
    return make_ell_prism_padded_by_bbox()


@pytest.fixture(scope="session")
def hollow_ball() -> bd.Solid:
    return make_hollow_ball()


@pytest.fixture(scope="session")
def sliver_face_part() -> bd.Solid:
    return make_sliver_face_part()


@pytest.fixture(scope="session")
def side_flat_dome() -> bd.Solid:
    """F-001: a part with NO +Z-facing planar face — `thicken` must refuse it, not guess."""
    return make_side_flat_dome()


@pytest.fixture(scope="session")
def open_shell() -> bd.Shell:
    return make_open_shell()


@pytest.fixture
def box_step(tmp_path: Path, box: bd.Solid) -> Path:
    return write_step(box, tmp_path / "box.step")


@pytest.fixture
def plate_step(tmp_path: Path, plate: bd.Solid) -> Path:
    return write_step(plate, tmp_path / "plate.step")


@pytest.fixture
def plate_with_corner_hole_step(tmp_path: Path, plate_with_corner_hole: bd.Solid) -> Path:
    return write_step(plate_with_corner_hole, tmp_path / "corner_hole.step")


@pytest.fixture
def through_hole_step(tmp_path: Path, plate_with_through_hole: bd.Solid) -> Path:
    return write_step(plate_with_through_hole, tmp_path / "through_hole.step")


@pytest.fixture
def ell_prism_step(tmp_path: Path, ell_prism: bd.Solid) -> Path:
    return write_step(ell_prism, tmp_path / "ell.step")


@pytest.fixture
def ell_profile_pad_step(tmp_path: Path, ell_prism_padded_by_profile: bd.Solid) -> Path:
    return write_step(ell_prism_padded_by_profile, tmp_path / "ell_profile_pad.step")


@pytest.fixture
def ell_bbox_pad_step(tmp_path: Path, ell_prism_padded_by_bbox: bd.Solid) -> Path:
    return write_step(ell_prism_padded_by_bbox, tmp_path / "ell_bbox_pad.step")
