"""T16 — geometric fixtures, GENERATED by build123d code. Never downloaded.

Every fixture is authored to reproduce one row of the Betti table in the benchmark's
`docs/metrics/topo_match.md`, so the parity assertions in the scoring tests are anchored
to the benchmark's own worked examples rather than to our implementation's opinion.

Betti convention: (b0, b1, b2) = (connected components, independent loops/tunnels, enclosed voids).
"""

from __future__ import annotations

from pathlib import Path

import build123d as bd

# --- valid fixtures ---------------------------------------------------------------


def make_box(size: float = 10.0) -> bd.Solid:
    """A plain prismatic block. Betti (1, 0, 0)."""
    return bd.Solid.make_box(size, size, size)


def make_plate_with_through_hole(
    length: float = 20.0, width: float = 20.0, thickness: float = 5.0, radius: float = 3.0
) -> bd.Solid:
    """A plate pierced by a through hole — a genuine tunnel. Betti (1, 1, 0)."""
    plate = bd.Solid.make_box(length, width, thickness)
    hole = bd.Solid.make_cylinder(radius, thickness * 3).locate(
        bd.Location((length / 2, width / 2, -thickness))
    )
    result = plate.cut(hole)
    return _as_solid(result)


def make_plate_with_blind_pocket(
    length: float = 20.0, width: float = 20.0, thickness: float = 5.0, radius: float = 3.0
) -> bd.Solid:
    """A plate with a blind pocket. Topologically trivial: Betti (1, 0, 0).

    This is the doc's explicit caution that blind features do not change topology.
    """
    plate = bd.Solid.make_box(length, width, thickness)
    pocket = bd.Solid.make_cylinder(radius, thickness / 2).locate(
        bd.Location((length / 2, width / 2, thickness / 2))
    )
    return _as_solid(plate.cut(pocket))


def make_two_disjoint_blocks(size: float = 5.0, gap: float = 10.0) -> bd.Compound:
    """Two separated blocks. Betti (2, 0, 0)."""
    a = bd.Solid.make_box(size, size, size)
    b = bd.Solid.make_box(size, size, size).locate(bd.Location((size + gap, 0, 0)))
    return bd.Compound(children=[a, b])


def make_hollow_ball(outer: float = 10.0, inner: float = 6.0) -> bd.Solid:
    """A sphere with a concentric spherical void. Betti (1, 0, 1)."""
    shell_outer = bd.Solid.make_sphere(outer)
    shell_inner = bd.Solid.make_sphere(inner)
    return _as_solid(shell_outer.cut(shell_inner))


def make_sliver_face_part(size: float = 10.0, notch: float = 0.02) -> bd.Solid:
    """A valid block carrying a face far below the advisory min-area threshold.

    The notch floor is ``notch**2`` mm^2 (default 4e-4 mm^2 < 1e-3 mm^2), which the
    benchmark's validity doc flags as ADVISORY only — it must never gate validity.
    """
    block = bd.Solid.make_box(size, size, size)
    cutter = bd.Solid.make_box(notch, notch, 1.0).locate(bd.Location((0.0, 0.0, size - 1.0)))
    return _as_solid(block.cut(cutter))


def make_side_flat_dome(radius: float = 10.0) -> bd.Solid:
    """A half-ball whose ONE planar face faces -X: the F-001 shape class.

    `abc_0365`'s top is a domed cylinder/torus blend with no +Z-facing planar face, so a
    position-based "top planar face" selector returns a SIDE face and any extrusion along
    its normal grows the part sideways while the metadata still claims Z. This fixture
    reproduces that topology in three lines: the only PLANE is the flat disc at X=0, whose
    outward normal is -X. Betti (1, 0, 0).
    """
    ball = bd.Solid.make_sphere(radius)
    cutter = bd.Solid.make_box(radius * 2, radius * 4, radius * 4).locate(
        bd.Location((-radius * 2, -radius * 2, -radius * 2))
    )
    return _as_solid(ball.cut(cutter))


# --- invalid fixtures -------------------------------------------------------------


def make_open_shell(size: float = 10.0) -> bd.Shell:
    """A box shell with its top face removed: not watertight, has naked edges."""
    box = bd.Solid.make_box(size, size, size)
    faces = sorted(box.faces(), key=lambda f: f.center().Z)
    return bd.Shell(faces[:-1])


# --- edited-pair fixtures (for diff / scoring tests) ------------------------------


def make_plate(length: float = 20.0, width: float = 20.0, thickness: float = 5.0) -> bd.Solid:
    """The un-edited input body used as the 'before' side of edit pairs."""
    return bd.Solid.make_box(length, width, thickness)


def make_plate_with_corner_hole(
    length: float = 20.0, width: float = 20.0, thickness: float = 5.0, radius: float = 2.0
) -> bd.Solid:
    """`make_plate` with a through hole in one corner: a LOCALIZED edit of `make_plate`."""
    plate = make_plate(length, width, thickness)
    hole = bd.Solid.make_cylinder(radius, thickness * 3).locate(bd.Location((4.0, 4.0, -thickness)))
    return _as_solid(plate.cut(hole))


def make_thicker_plate(
    length: float = 20.0, width: float = 20.0, thickness: float = 6.0
) -> bd.Solid:
    """`make_plate` with the thickness dimension changed: a GLOBAL edit."""
    return bd.Solid.make_box(length, width, thickness)


# --- the abc_0352 class: identical bbox, different CROSS-SECTION -------------------
#
# run-003 F-005 Q2: a `thicken` candidate padded the +X face with a box spanning the whole
# bounding RECTANGLE instead of extruding the face's own L-shaped profile. Every bbox extent
# matched the ground truth exactly while the body carried +65.7% unintended volume, so the
# agent's extent-only intent check passed a wrong answer. These fixtures reproduce that
# geometry in miniature: an L-section prism, the RIGHT pad (face profile swept) and the WRONG
# pad (bounding rectangle swept). Both pads produce the SAME bounding box.

ELL_LENGTH = 48.0
ELL_WIDTH = 60.0
ELL_HEIGHT = 38.0
ELL_NOTCH_WIDTH = 30.0
ELL_NOTCH_HEIGHT = 20.0
ELL_PAD_DEPTH = 12.0
#: Area of the L-shaped +X face — the cross-section a CORRECT pad sweeps.
ELL_FACE_AREA = ELL_WIDTH * ELL_HEIGHT - ELL_NOTCH_WIDTH * ELL_NOTCH_HEIGHT
#: Area of that face's BOUNDING RECTANGLE — the cross-section the DEFECTIVE pad sweeps.
ELL_BBOX_FACE_AREA = ELL_WIDTH * ELL_HEIGHT


def make_ell_prism() -> bd.Solid:
    """An L-section prism swept along X: the 'before' body of the abc_0352 pair."""
    block = bd.Solid.make_box(ELL_LENGTH, ELL_WIDTH, ELL_HEIGHT)
    notch = bd.Solid.make_box(ELL_LENGTH * 2, ELL_NOTCH_WIDTH, ELL_NOTCH_HEIGHT).locate(
        bd.Location((-ELL_LENGTH / 2, ELL_WIDTH - ELL_NOTCH_WIDTH, ELL_HEIGHT - ELL_NOTCH_HEIGHT))
    )
    return _as_solid(block.cut(notch))


def make_ell_prism_padded_by_profile() -> bd.Solid:
    """The CORRECT pad: the +X face's own L profile, swept ``ELL_PAD_DEPTH`` along +X."""
    base = make_ell_prism()
    pad = base.moved(bd.Location((ELL_PAD_DEPTH, 0.0, 0.0)))
    return _as_solid(base.fuse(pad))


def make_ell_prism_padded_by_bbox() -> bd.Solid:
    """The DEFECTIVE pad: the face's BOUNDING RECTANGLE swept the same distance.

    Same bbox as :func:`make_ell_prism_padded_by_profile`, same X extent, same requested
    +12 mm — plus ``ELL_NOTCH_WIDTH * ELL_NOTCH_HEIGHT * ELL_PAD_DEPTH`` mm^3 of material
    the instruction never asked for.
    """
    slab = bd.Solid.make_box(ELL_PAD_DEPTH, ELL_WIDTH, ELL_HEIGHT).locate(
        bd.Location((ELL_LENGTH, 0.0, 0.0))
    )
    return _as_solid(make_ell_prism().fuse(slab))


# --- helpers ----------------------------------------------------------------------


def _as_solid(shape: bd.Shape) -> bd.Solid:
    solids = shape.solids()
    if len(solids) == 1:
        return solids[0]
    raise AssertionError(f"fixture produced {len(solids)} solids, expected exactly 1")


def write_step(shape: bd.Shape, path: Path) -> Path:
    """Persist a fixture to STEP so filesystem-facing code paths can be exercised."""
    path.parent.mkdir(parents=True, exist_ok=True)
    bd.export_step(shape, str(path))
    return path
